### ISSUE TITLE
HF UI doesn't show user what is happening during dynamic bind

### ISSUE THREAD

**Issue by wjimenez5271** [hobbyfarm/hobbyfarm#10]
When using dynamic bind, the user gets a screen that looks like this for several minutes while the VM is provisioning. This is confusing to the user as it looks like something is broken. The UI should indicate that we are waiting on a new VM
<img width="1362" alt="Screen Shot 2019-12-17 at 9 58 42 AM" src="https://user-images.githubusercontent.com/322834/71021821-fc28f980-20b3-11ea-909f-71c14e240695.png">

**Comment by hall** [comment]
This is fixed; the UI now shows this during a dynamic bind:
![Screenshot from 2020-03-04 21-05-32](https://user-images.githubusercontent.com/32495955/75940806-ec84aa00-5e85-11ea-83f3-f07dfe40ae05.png)
