### ISSUE TITLE
Bad service account secrets in local dev environment

### ISSUE THREAD

**Issue by debianmaster** [hobbyfarm/hobbyfarm#103]
**What happened**:
Document does not specify default username/password
default username password `admin/admin` does not work nor the registration works

**What you expected to happen**:
should login into admin ui or ui

**How to reproduce it (as minimally and precisely as possible)**:
./dev.sh

**Anything else we need to know?**:

**Environment**:
k3d 

- Gargantua version:
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
MacOSX

**Comment by hall** [comment]
Hi @debianmaster! I think the `dev.sh` script should probably be removed. Try using the `compose.sh` script instead.

**Comment by debianmaster** [comment]
@hall  when using `compose.sh` can you help me how to access ui?     is there a default user/password to login?       i cant seem to find on documentation.  i tried  admin/admin

**Comment by hall** [comment]
Did you use `npm` or the `compose.sh` script from the UI repo as well? https://github.com/hobbyfarm/ui/blob/master/CONTRIBUTING.md#local-development

**Comment by debianmaster** [comment]
@hall these are the steps i ran
```
git clone https://github.com/hobbyfarm/hobbyfarm
cd hobbyfarm
./compose.sh build
./compose.sh up

docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                     NAMES
bcc53cebcc2a        rancher/k3s:v1.17.2-k3s1   "/bin/k3s server --h…"   21 minutes ago      Up 21 minutes       0.0.0.0:16220->6443/tcp   hf-k3d

```

```
git clone https://github.com/hobbyfarm/ui
cd ui
cp src/environments/environment.local.example.ts src/environments/environment.local.ts
cat src/environments/environment.local.ts
export const environment = {
  production: false,
  server: "http://localhost:16220",
};
npm i
npm run start:local
open http://localhost:4200/
# use admin/admin for email and password
```

<img width="1414" alt="Screenshot 2020-05-07 at 2 25 57 AM" src="https://user-images.githubusercontent.com/1439169/81214251-269b3500-900a-11ea-91b2-0204a2932e14.png">

**Comment by hall** [comment]
Thanks for all of the details and sorry this process is currently so confusing! I think you'll need to do the same thing with the gargantua repo (that's the backend that the ui is trying to authenticate to).

**Comment by debianmaster** [comment]
additional to steps above i also  ran  compose.sh up inside https://github.com/hobbyfarm/gargantua.   repo.   got this log 

```
hf-garg | E0506 19:12:00.839763    2402 config.go:417] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: error reading /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: data does not contain any valid RSA or ECDSA certificates
hf-garg | E0506 19:12:00.839783    2401 config.go:417] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: error reading /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: data does not contain any valid RSA or ECDSA certificates
hf-garg | F0506 19:12:00.839927    2402 main.go:88] read empty token from file "/var/run/secrets/kubernetes.io/serviceaccount/token"
hf-garg | F0506 19:12:00.840158    2401 main.go:88] read empty token from file "/var/run/secrets/kubernetes.io/serviceaccount/token"
```

no luck on UI

**Comment by debianmaster** [comment]
fixed it by running this manually

```
docker exec hf-k3d sh -c '
                cd /var/run/secrets/kubernetes.io/serviceaccount
                secret=$(kubectl get secret \
                        -o name  \
                    | grep "default-token")
                kubectl get "$secret" \
                    -o "jsonpath={.data.ca\.crt}" \
                    | base64 -d \
                    > ca.crt
                kubectl get "$secret" \
                    -o "jsonpath={.data.namespace}" \
                    | base64 -d \
                    > namespace
                kubectl get "$secret" \
                    -o "jsonpath={.data.token}" \
                    | base64 -d \
                    > token
            '
```

thanks for your help

**Comment by hall** [comment]
Glad you got it fixed! I'm going to reopen this so we can solve the underlying issue.

**Comment by ebauman** [comment]
Sorry for the confusion re: dev.sh :(

**Comment by ebauman** [comment]
dev.sh was removed so I am closing this. If there is a need to reopen please do so.
