### ISSUE TITLE
Guide for creating scenarios

### ISSUE THREAD

**Issue by debianmaster** [hobbyfarm/hobbyfarm#104]
**What would you like to be added**:
guide for creating custom scenario
any example scenarios repo? and how to upload them to my current installation?

**Why is this needed**:
i would like to use hobbyfarm for enabling our product online, is there a way to create custom scenarios?

**Comment by jggoebel** [comment]
Maybe https://github.com/hobbyfarm/docs/blob/master/entities.md#scenario can help you.
If you still need further assistance you can reopen this issue.
