### ISSUE TITLE
Access Any User's scenariosession as Admin

### ISSUE THREAD

**Issue by alex-boxboat** [hobbyfarm/hobbyfarm#11]
Admins should be able to get access to any user's scenariosession so that they can help a user debug issues.  While sharing bash history and users is nice, it is probably more important that an admin can just run commands to verify that a user setup the environment correctly or that the scenario is working as expected.  Being able to share bash history and see what a user exactly did can be a later enhancement.

**Comment by hall** [comment]
See issue #12 for a few related/clarifying comments.

**Comment by jggoebel** [comment]
Closing in favor of https://github.com/hobbyfarm/hobbyfarm/issues/133
