### ISSUE TITLE
Access any scenario as Admin

### ISSUE THREAD

**Issue by alex-boxboat** [hobbyfarm/hobbyfarm#12]
If you are an admin within hobbyfarm, you should be able to see and join any currently available/running modules from the normal hobbyfarm ui without adding a new access code.  This way, an admin can join a given training and help debug any steps in an issue without needing to add an access code for every training they have to help with.

**Comment by jggoebel** [comment]
As far as i can see this will not be implemented. The admin could just add the access code and use the print functionality to display the contents without the need of provisioning a VM.
