### ISSUE TITLE
GetAccessCode in pkg/accesscode does not respect expiredOk parameter

### ISSUE THREAD

**Issue by ebauman** [hobbyfarm/hobbyfarm#120]
**What happened**: pkg/accesscode has a method `GetAccessCode` accepting two parameters, `code string` and `expiredOk bool`. Recent testing confirms that this method does not honor the `expiredOk` parameter, as evidenced by https://github.com/hobbyfarm/gargantua/blob/4b9951b56fdc4a9f8155145d48702abd0af6b199/pkg/accesscode/accesscode.go#L83 (wherein the `false` value is actually where `expiredOK` should be plugged in). 

**What you expected to happen**: Passing in a bool to expiredOk should alter behavior of the access code query. 

**How to reproduce it (as minimally and precisely as possible)**: Call `GetAccessCode` and pass in `true` for `expiredOk`. Observe the return of `"insane result found"` as an error. 

**Environment**:
- Gargantua version: `master`

**Comment by jggoebel** [comment]
Do we still need this behaviour? GetAccessCode is never called with true right now. Did you have something specific in mind where this would be needed?
