### ISSUE TITLE
UI: file type for logos is hardcoded

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#127]
**What happened**:
When I specify the logo and other icons as base64, the file type is hardcoded to jpg while the default images are used as SVG. 

**What you expected to happen**:
Do not use a file type ad let me use a base64 encoded SVG.

**How to reproduce it (as minimally and precisely as possible)**:
Use a base64 encoded SVG in the ui config as logo.

**Anything else we need to know?**:

This is an example of where this is done:
https://github.com/hobbyfarm/ui/blob/452fa4b2bb02bb30067570722ad3026aa1cb1afc/src/app/login/login.component.ts#L38

**Comment by ebauman** [comment]
I have started work on this. Plan is to adjust `config.json` to allow for specification of content type, then just serve the `src` w/ that.

**Comment by ebauman** [comment]
Actually, new direction on this. 
Going to allow for default location of built-in images, but then via config.json allow for mounting of files into the container to substitute.
