### ISSUE TITLE
UI: custom css

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#128]
In some cases it may make sense to add custom css to the frontend. Currently we solve this with adding style html code to the scenario steps.

It may make sense to get the ability to add custom css to the config.json to make the styling more flexible for users.

**Comment by ebauman** [comment]
In #127 I made a change so that users can mount their own images into the container, and reference them in `config.json`. Would a similar approach be workable here? 

note: I don't yet know how feasible this is. there may be some angular weirdness I haven't accounted for.

**Comment by ebartz** [comment]
I think just referencing to a file would be enough. Important is that this get loaded after all the other css files.
