### ISSUE TITLE
UI: view scenario

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#131]
The only way to have a look at the scenario content is to actually start the scenario which causes the virtual machines to be provisioned.

It would be helpful if a student could only review the exams content without the need of provisioning it.

If the student is in "view mode" there could be a button which allows them to actually start the scenario which then creates the VM's if needed.

**Comment by jggoebel** [comment]
Is this resolved with the new print functionality?

**Comment by jggoebel** [comment]
Resolved with the print functionality.
