### ISSUE TITLE
admin-ui: Basic admin reporting

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#132]
As an instructor I want to have a overview of currently active users.

There are a few use-cases that would be useful:
1) I would like to see which of the students are currently logged in to the system.
2) I would like to see which of the students have started which scenario.
3) I would like to see which of the student currently owns which virtual machine.
4) I would like to see the progress of a student in a scenario. As the scenario is divided into steps, it would be useful to see which is the current active step and science when the student is working on it.

**Comment by jggoebel** [comment]
All of this features (Except 3.) are implemented in the new Progress Dashboard.
I will open a new issue for the virtual machine ownership.
