### ISSUE TITLE
admin-ui: get access to student terminal

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#133]
If a student is stuck i a session it would be helpful if the instructor could get at least a read-only access to the students terminal.

It would be even more awesome if the instructor could get access to the terminal to help with things.

**Comment by jggoebel** [comment]
This is currently in work by @PhPrinz

**Comment by jggoebel** [comment]
Introduced in https://github.com/hobbyfarm/admin-ui/pull/120
