### ISSUE TITLE
Allow user to send Ctrl-C to interactive console

### ISSUE THREAD

**Issue by alan-copeland-keysight** [hobbyfarm/hobbyfarm#134]
**What would you like to be added**:

Allow user to send Ctrl-C to interactive console

**Why is this needed**:

I find myself refreshing the page if I've run a command that doesn't return, e.g. when -f following logs from kubectl.

**Comment by ebauman** [comment]
This should work today. It's been tested in Chrome and FF as working. 
What browser/OS combo are you using?

**Comment by alan-copeland-keysight** [comment]
Chrome on a Mac, but using a Windows keyboard. I've got some weak magic for key mapping that's mucking with Ctrl-C for copy/paste on Windows VM's. I'll assume thats borked, not HobbyFarm. Thanks for the response!

@hognala on Twitter

**Comment by jggoebel** [comment]
Can we close this?
