### ISSUE TITLE
UI & admin UI: enhanced styling for code blocks

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#135]
As a content creator it would be great if I would not just define code blocks but also choose a language. Especially for yaml or other languages it makes reading much easier when things are highlighted the right way.

It probably depends on how this is implemented currently but there are good frameworks out there which could solve that issue:
https://medium.com/wizdm-genesys/syntax-highlighting-in-angular-b192f25d17b2

**Comment by jggoebel** [comment]
Syntax highlighting for python, Dockerfiled, yaml, json and go implemented in https://github.com/hobbyfarm/ui/pull/83

**Comment by jggoebel** [comment]
https://github.com/hobbyfarm/ui/pull/83 was merged. This should be working now!
