### ISSUE TITLE
Gargantua: bad performance with many open dynamicbindrequests

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#137]
**What happened**:
In some cases after large trainings there will be many (50k+) dynamicbindrequests in etcd. For some reason it takes very long to even query them. In some cases gargantua seems to check them all which causes high cpu load 

**What you expected to happen**:
Gargantua should not check for old ressources. It may even delete old ones after some time so etcd does not have to store so many of them when they are not needed anymore.

**How to reproduce it (as minimally and precisely as possible)**:
Work with an environment with over 50k dynamicbindrequests.

**Environment**:
- Gargantua version: hobbyfarm/gargantua:v0.1.9
- UI/Admin version: hobbyfarm/admin-ui:v0.2.3; hobbyfarm/ui:v0.4.7
- Kubernetes version (use `kubectl version`): 1.20 k3s with etcd
- Cloud provider or hardware configuration: hetzner cx51 (8 Cores; 32GB memory)
- OS (e.g: `cat /etc/os-release`): ubuntu-20.04

**Comment by ebauman** [comment]
How many sessions occurred in this training?  50k DBRs is....excessive.

**Comment by ebartz** [comment]
The environment was running for a couple of weeks and performance got worse over time. Mostly we have 15 - 20 attendees which then go through 8 - 12 scenarios. Each scenario usually has 1 or 2 VMs. Some attendees tend to restart their scerarios from time to time and we also have multiple trainers using the environment. So it adds up... Anyhow, why are there DBRs even after the VMs don't exist anymore? For statistics or something?

**Comment by ebartz** [comment]
This issue seems to be resolved with the latest release as DBRs get deleted automatically.

**Comment by jggoebel** [comment]
This should be resolved as of https://github.com/hobbyfarm/gargantua/pull/80
DBRs are now being deleted when the session is finished.
