### ISSUE TITLE
UI: overview of user ressources

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#138]
When a user is not using their VM's there should be a way in which they can see that there are still VMs bound by them.

Also I'm thinking of making it possible to assign a workload to a user for a couple of days. Especially if the scenario means working with larger applications over a period of 2 oder 4 days, it would be helpful if the user could resume using his VM on the next training day.

I am thinking of introducing a new tab to the UI that lets you see already scheduled ressources or scenarios. Something like scenarios in progress.

That Menu would pretty much look the same as the scenarios overview but it would give a user the ability to resume or terminate scenarios that are still running.

And if we implement something like "resume" it would be great if it would go back to the last step that was open.

**Comment by jggoebel** [comment]
This should be resolved by the progress implementation.
