### ISSUE TITLE
UI & Admin UI: Solution for hidden text in scenarios

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#139]
It would be awesome if there could be hidden text fields as a special type of codeblock.

In some cases I would like a user to troubleshoot in a scenario. There it would be helpful to have an option to offer tips if the users need them.

I am thinking of some sort of hidden codeblock.

As trainer I would like to specify something like this:
```
  `` `hidden
  This is awesome!
  `` `
```

In a scenario the user should see this:

![image](https://user-images.githubusercontent.com/6342767/123380865-43892380-d590-11eb-9c8d-6cb6c585b088.png)

With an onClick() event the user should be able to see the codeblock.

We are currently doing it like this:

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapsible

**Comment by ebartz** [comment]
Maybe just offering code blocks is not the best idea. Might be useful to just find a way to collapse content in some way. In one Lab we did also something like this:

```
<button onclick="
    var x = document.getElementById('HiddenElement');
    if (x.style.display == 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }">Click me</button>
<div id="HiddenElement" style="display:none">
# This is some help
-```ctr:node1
kubectl get po -A
-```
</div>

```
Would be awesome if we could find a way to template this kind of thing. I don't know how exactly but maybe someone has a nice idea.

**Comment by hall** [comment]
The [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) HTML element was made for this. A bit verbose but doesn't require any js or angular modifications.

**Comment by jggoebel** [comment]
Implemented in https://github.com/hobbyfarm/ui/pull/83

**Comment by jggoebel** [comment]
This issue is solved as of https://github.com/hobbyfarm/ui/pull/83
