### ISSUE TITLE
No Default Credentials for Admin or User when installing with Helm Chart

### ISSUE THREAD

**Issue by thewritingstew** [hobbyfarm/hobbyfarm#140]
**What happened**: Installed HobbyFarm using Helm chart and had no way to log in.

**What you expected to happen**: Expected admin/admin or something similar to work as initial login credentials, or expected instructions on how to log in. (I'm happy to contribute to some documentation if that is needed)

**How to reproduce it (as minimally and precisely as possible)**: Use Helm chart install command to HobbyFarm on kubernetes cluster running on VMWare Workstation pro.

**Anything else we need to know?**:

**Environment**: 
- Gargantua version: Whatever is called in helm chart
- UI/Admin version: whatever is called in helm chart
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: VMWare Workstation Pro 15 running on Windows 10, hosting Linux VM with kubernetes
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.2

**Comment by ebartz** [comment]
Hi @thewritingstew,

when you deploy hobbyfarm the first time there is not much data which is deployed by default.

In this repo you will find an example yaml for creating an initial admin user:
https://github.com/hobbyfarm/hobbyfarm/blob/master/cicd/seed-data/user.yaml

Also you can go to the UI and register a new user from there. With kubectl you can then give admin permissions like this:

```
kubectl get users
NAME           AGE
u-dbpy3abcabc   10s
```

After you found your user, go ahead and edit it:

```shell
kubectl edit user u-dbpy3abcabc  
```

Make sure to set the admin flag to true and save.
```yaml
apiVersion: hobbyfarm.io/v1
kind: User
metadata:
  creationTimestamp: "2021-07-16T12:46:47Z"
  generation: 2
  name: u-dbpy3abcabc  
  resourceVersion: "5475"
  uid: a6155f1d-a58f-40ba-9bae-1bbe226a8a4c
spec:
  access_codes:
  - foobar
  admin: true
  email: foo@bar.foo
  id: u-dbpy3abcabc
  password: **************
```

After this you would be able to login as admin.

Hope this helps.

**Comment by thewritingstew** [comment]
Thank you @ebartz. I added a user as described, but was unable to log in. Login pages are unresponsive. I was going to use hobbyfarm for a student project, but at this point I will have to move on given the timing and my unfamiliarity with the project. Thanks for your help. This ticket can probably be closed due to lack of user knowledge. =)
