### ISSUE TITLE
Feature: Scenarios as Code

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#150]
Creating scenarios in the backend can be a job that takes much time. To work on a scenario as a team currently is not that easy.

Instead of just editing the steps in the backend, it would be great if we could manage the content of a scenario in git.

So creating a scenario should still happen in the admin backend but instead of manually maintaining the steps, I would like to use a git url from where hobbyfarm then pulls the content.

This would also give students the ability to improve scenarios by submitting pull requests to the content.

It would make sense to at least specify the git uri and the branch.

It would also be great if you could then reference to media files contained in that git repository.

**Comment by jggoebel** [comment]
We do not need this feature right now, as we are using a pipeline to bring scenarios into hobbyfarm.
