### ISSUE TITLE
UI: Terminal Themes

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#152]
Im some cases it might be good to have he choice between different terminal colors.

I very much like the different types of the solarized theme: https://ethanschoonover.com/solarized/

![image](https://user-images.githubusercontent.com/6342767/131504453-fc34d348-0cca-4ad1-8f41-e9b1f62e4921.png)

![image](https://user-images.githubusercontent.com/6342767/131504474-a63dc102-8523-49bb-b05f-d2278fdcc4e9.png)

It think it would be nice if the user could have a setting to choose between a light and dark terminal theme.

**Comment by jggoebel** [comment]
Would also be nice to have a dark theme for the whole site, including the markdown

**Comment by jggoebel** [comment]
https://github.com/hobbyfarm/ui/pull/90 was merged
