### ISSUE TITLE
one cluster - multiple hobbyfarm instances

### ISSUE THREAD

**Issue by ebartz** [hobbyfarm/hobbyfarm#153]
Currently there are a lot of resources which do not live inside of a namespace. On the other hand some resources live hardcoded in the hobbyfarm namespace.

I would like to be able to have multiple hobbyfarm instances running in the same cluster. Therefore this needs to be changed.

**Comment by wzrdtales** [comment]
when i tested this today i really wondered that you don't use an actual database. so this project literally will saturate the clusters own resources by clogging the etcd? The bigger blocker for me is: this project can't really run in shared environments, for multiple reasons, but especially b/c the etcd speed might not be guaranteed and can affect the performance of the rest of the cluster.

**Comment by jggoebel** [comment]
This issue was resolved in #163
