### ISSUE TITLE
UI does not display an error when attempting to create a ScheduledEvent with duplicate name

### ISSUE THREAD

**Issue by ebauman** [hobbyfarm/hobbyfarm#17]
Admin UI should display an error if a user is attempting to create a scheduled event that has the same name as another SE. 
Currently, the UI allows this to proceed as far as calling the API server, which returns an error. That error is not caught nor displayed, and the user's scheduled event seemingly disappears into the void.

**Comment by jggoebel** [comment]
I could not reproduce this issue.
Does it still occure to you? @ebauman
