### ISSUE TITLE
Environment availability queried based on env display_name instead of object name

### ISSUE THREAD

**Issue by ebauman** [hobbyfarm/hobbyfarm#18]
When using the scheduled event creation workflow, the admin ui currently uses the display_name value of the environments for querying w/r/t availability. 
Instead, it needs to be using the object name of the environments. 

https://github.com/hobbyfarm/admin-ui/blob/34799be52b71b29727fc6719d55001d5462e56e8/src/app/event/new-scheduled-event/new-scheduled-event.component.ts#L211

**Comment by jggoebel** [comment]
This should have fixed it:
https://github.com/hobbyfarm/admin-ui/commit/4adb16a25747b3afe0b197b64a9bed01aace7196
