### ISSUE TITLE
Scenario Import/Export

### ISSUE THREAD

**Issue by Oats87** [hobbyfarm/hobbyfarm#20]
I should be able to export/import my scenarios.

This one likely needs API support. 

Maybe just upload a giant b64 bundle? hm

**Comment by Roland0** [comment]
This would be very useful.

**Comment by hall** [comment]
How about a tarball and/or zip of the k8s resources in yaml format? I'm not sure what the intended use case is but that would also allow scripting the process through `kubectl` (as well as basic changes such as removing or adding scenarios in an existing bundle vs a b64 blob).

**Comment by jggoebel** [comment]
Is this still required? I am not seeing the advantage over using `kubectl get scenarios -o yaml` and then apply them again later on.
