### ISSUE TITLE
When creating scenarios, vm type selector is funky

### ISSUE THREAD

**Issue by Oats87** [hobbyfarm/hobbyfarm#23]
When creating scenarios, the VM selector is funky. It will auto populate to `ubuntu1604-docker1` for example, but you'll have to select another VM type then select back to `ubuntu1604-docker` in order to be able to add that vm type.

**Comment by jggoebel** [comment]
I believe this issue does not exist anymore. At least i could not reproduce it. 
Pls reopen if this issue still exists.
