### ISSUE TITLE
reverting to a non-stable api version

### ISSUE THREAD

**Issue by hall** [hobbyfarm/hobbyfarm#26]
**What would you like to be added**:
Is it too late to revert the apis to `v1alpha1`? Is it worthwhile?

**Why is this needed**:
I don't think this project is stable and using `v1` doesn't match what the k8s community expects.

**Comment by hall** [comment]
Right -- it should only be important if anyone builds something on top of hobbyfarm. To some degree, that's what we're doing with the helm chart but, it being under the same github group, that shouldn't be an issue. I'm fine with whatever decision the rest of you come up with; I just wanted to be sure that we have the discussion sooner rather than later.

**Comment by jggoebel** [comment]
The project should now be stable enough to use v1.
Reverting to v1alpha1 is now near the impossible. We are even implementing v2 on some CRDs before the 2.0.0 HF release.
