### ISSUE TITLE
Gargantua tries to create thousands of DynamicBindRequests when there is not a satisfactory DynamicBindConfiguration

### ISSUE THREAD

**Issue by Oats87** [hobbyfarm/hobbyfarm#27]
**What happened**: When creating dynamic bind VM's, if a VMC cannot be bound due to a lack of pre-existing VM's or a non-adequate DBC (or if the environments that are available do not have capacity to fulfill the DBR) then Gargantua will kick back the DBR after expiring it. A vicious cycle occurs which has Gargantua continuously created DBR's as it flip-flops between bind modes.

**What you expected to happen**: Gargantua should probably stop trying to create DBR's.

**How to reproduce it (as minimally and precisely as possible)**: Just create a VMC (with corresponding SS) that wants to be dynamically bound, but have a non-correctly configured DBC.

**Anything else we need to know?**: No

**Environment**:
- Gargantua version: 0.0.3
- Kubernetes version (use `kubectl version`): Doesn't matter.
- Cloud provider or hardware configuration: Doesn't matter.
- OS (e.g: `cat /etc/os-release`): Doesn't matter.

**Comment by jggoebel** [comment]
This can be closed as we got rid of DBRs completely.
