### ISSUE TITLE
automated github pages builds are unreliable

### ISSUE THREAD

**Issue by hall** [hobbyfarm/hobbyfarm#4]
Not sure if there's anything we can do about this but the GitHub Pages builds aren't reliably adding the latest release to the `index.yaml` file.

    curl -L hobbyfarm.github.io/hobbyfarm/index.yaml

As a workaround, the pages can be updated manually with a personal access token:

    curl -u <username>:<token> -X POST https://api.github.com/repos/hobbyfarm/hobbyfarm/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json"

**Comment by jggoebel** [comment]
i believe this is not an issue anymore
