### ISSUE TITLE
Content without virtual machine should be centered

### ISSUE THREAD

**Issue by jggoebel** [hobbyfarm/hobbyfarm#472]
**What happened**:
When using scenarios without virtual machines the content is stretched to the full width of the page. This looks very weird.

**What you expected to happen**:
We should cap the width of the content to 50% of the screens width and center it.
A little bit tricky could be courses that have a VM when the scenario does not. In This case we should also only display the content and hide the VirtualMachine

**How to reproduce it (as minimally and precisely as possible)**:
Create a scenario without virtual machines (content only scenario) and start it to view the stretched screen

**Anything else we need to know?**:

**Environment**:
- Gargantua version:
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by tanemlu** [comment]
I'll start working on this issue :)

**Comment by jggoebel** [comment]
Fixed in https://github.com/hobbyfarm/ui/pull/212
