### ISSUE TITLE
Does it work ?

### ISSUE THREAD

**Issue by gilsdav** [hobbyfarm/hobbyfarm#73]
Hobbyfarm examples artifacts and [this HELM chart](https://github.com/hobbyfarm/hobbyfarm) don't work with RancherVM.
They use this terraform template.
Do Hobbyfarm works with RancherVM ?

**Comment by ebauman** [comment]
I believe there is still work to be done in this area.

**Comment by ebauman** [comment]
RancherVM project is dead and not looking to be revived. 
Recommended to move to mature version of product w/ usage of a provider such as AWS, DigialOcean, etc.

**Comment by dgilsonAfelio** [comment]
Because RancherVm is dead, I asked to add kubevirt support: https://github.com/hobbyfarm/hobbyfarm/issues/310

**Comment by gilsdav** [comment]
Because RancherVm is dead, I asked to add kubevirt support: https://github.com/hobbyfarm/hobbyfarm/issues/310
