### ISSUE TITLE
FR: Be able to clone scenarios

### ISSUE THREAD

**Issue by Roland0** [hobbyfarm/hobbyfarm#74]
Just an idea, I'm not sure of the feasibility etc

Something like this:

![clone](https://user-images.githubusercontent.com/1220654/74927774-29ee2f80-53d0-11ea-9aba-ef28715119b3.png)

**Comment by hall** [comment]
Hey @Roland0, thanks for the suggestion!

What's the use case here? Do you have highly similar scenarios and just don't want to rewrite the others from scratch? Or are you trying to have copies of the same scenario?

Not sure if this helps but, in the meantime, this can be done with `kubectl` (if you only need to do it once or twice); e.g., just replace `<old-scenario>` and `<new-scenario>` here:

```
OLD=<old-scenario>
NEW=<new-scenario>
kubectl get -oyaml scenarios $OLD | sed "s|$OLD|$NEW|g" | kubectl apply -f -
```

**Comment by Roland0** [comment]
You're welcome!

Either of these = {Do you have highly similar scenarios and just don't want to rewrite the others from scratch,Or are you trying to have copies of the same scenario?}

The current use case: I'm just updating a scenario to have slightly differing version numbers (with some other small changes),  cloning either the whole scenario or the steps would be useful. At the moment I'm simply copy/pasting markdown.

I don't have access to the backend at present, so the kubectl workaround isn't do-able, it needs to be a UI feature.

Thanks!

**Comment by hall** [comment]
Yeah, I figured `kubectl` wasn't an option but doesn't hurt to throw it out there :smile:

I don't think I'm following what you're trying to do. If you're _updating_ an existing scenario, why do you want to keep an old version of the scenario? Are you trying to offer slightly different versions of the same scenario (e.g., one using Helm 2 and another using Helm 3)?

**Comment by Roland0** [comment]
> why do you want to keep an old version of the scenario

Because there is no kind of lock/dependency, when a scenario is included in an event, it is mutable. I could, for example, do a broken or partial update, and it would change someones event, breaking it, "this worked yesterday" :slightly_smiling_face:  

There is also a need for this simply as a quick way to create new scenarios, a clone => edit => publish type pattern, IMO.

Thanks again.

**Comment by Roland0** [comment]
> Are you trying to offer slightly different versions of the same scenario (e.g., one using Helm 2 and another using Helm 3)?

Good guess! another use case! :slightly_smiling_face:

**Comment by hall** [comment]
> Because there is no kind of lock/dependency, when a scenario is included in an event, it is mutable.

Maybe the answer here is to implement some sort of versioning for scenarios.

> There is also a need for this simply as a quick way to create new scenarios, a clone => edit => publish type pattern, IMO.

Unless I'm mistaken, this would only be useful if your scenarios are _really_ similar; otherwise, why not start with a blank scenario?

> Good guess! another use case!

We don't want to add/support theoretical use cases; only those with a legitimate need. In this particular case, Helm 2 vs 3, I would say update to 3 and leave 2 in the dust! However, maybe we should consider creating scenario variables (just one option, not sure if that's a good idea).

Let's also see what @ebauman and @Oats87 say; they'd know better than I and might say that you're original suggestion is the way to go.

**Comment by Roland0** [comment]
> Unless I'm mistaken, this would only be useful if your scenarios are really similar; otherwise, why not start with a blank scenario?

Or when you have many that need slight changes, if you had say 10+ that need slight changes.

Just an idea, I would have found a it useful. 

We're also thinking of being able to have the scenarios git-driven.

**Comment by hall** [comment]
Yeah, I'm not saying it wouldn't be useful; I'm just not understanding _why_ you might want 10+ scenarios that are similar. What's your use case? Maybe there's a better solution to just copy-pasting scenarios (like gotemplating).

For gitops, we've created an internal helm chart that depends on `hobbyfarm/hobbyfarm` and creates scenarios and environments and such with templates. Then you can point something like Flux or ArgoCD to that repo and deploy changes from a branch. It would be nice to have this templating in the upstream chart but a chart can only access files within its own context/directory.

**Comment by jggoebel** [comment]
My suggestion would be this Feature: https://github.com/hobbyfarm/hobbyfarm/issues/206

This would enable us to fill key/value date based on ScheduledEvent / User Basis.
It would enable us to use the same scenario with different versions / values in the markdown.

**Comment by jggoebel** [comment]
See last comment
