### ISSUE TITLE
Cannot delete scheduled event

### ISSUE THREAD

**Issue by Roland0** [hobbyfarm/hobbyfarm#75]
When attempting to delete event nothing happens other than an error/warning shows:

![image](https://user-images.githubusercontent.com/1220654/74930377-5ce6f200-53d5-11ea-9354-5b77b0f24fc7.png)

**Comment by ebauman** [comment]
Delete is improperly available in the admin ui, but not correctly implemented in gargantua.
It should be disabled until suck time as the garg API firms up for that functionality.

**Comment by PhilipAB** [comment]
Can be closed. The Garg API supports this as of https://github.com/hobbyfarm/gargantua/pull/80.

**Comment by jggoebel** [comment]
As referenced by @PhilipAB this feature is now implemented.
