### ISSUE TITLE
Changes to existing event do not save

### ISSUE THREAD

**Issue by Roland0** [hobbyfarm/hobbyfarm#76]
Possibly related to #60 ?

**Comment by hall** [comment]
I'm not able to reproduce this. Do you have an error message or a minimal (non-)working example?

**Comment by jggoebel** [comment]
I was experiencing the same issue as @Roland0.
It seems like events that are in progress can not be updated. 

Steps to reproduce:
1. Create a new Event that starts in the future
2. Update some fields like the title or description
3. Save updates (This works)
3. Update starting time to be in the past so the event status states "in progress"
4. Save starting time (This works)
5. Try to update title again
6. Save (This fails and the title is the same as from step 2)

**Comment by jggoebel** [comment]
Looking at Gargantuas scheduleevent.go:311 this seems to be intended...

@Oats87 do you still remember your intentions behind this?

**Comment by ebauman** [comment]
I can speak for him here, the intention was "do no harm" basically. We wanted to prevent a scenario whereby edits of the scheduledevent would result in deletion of existing VMs. 

I recognize that may need to happen, though, and so I am happy to see progress on this issue. As long as we are very clear with the admin that deleting an active SE *will* impact users, it should be okay.
