### ISSUE TITLE
Local Development via docker-compose

### ISSUE THREAD

**Issue by caleblloyd** [hobbyfarm/hobbyfarm#78]
Hello, I'm joining the party from BoxBoat, I have been working with @hall on standing HobbyFarm up.  Wanted to get tied in and start sending merges upstream!

I would like to propose streamlining local development via `docker-compose`.  Along with these changes, there is also some general CI improvements that I think could benefit the project.

## Backend Local Dev

- Local Dev services:
  - [kind](https://github.com/kubernetes-sigs/kind) image to run control plane for CRD storage
  - `kubectl` image to connect to the kind cluster, and run environment initialization
  - `garg` image that mounts source code and runs watch loop, rebuilding when code changes
- Observations:
  - `garg` currently listens on Port 80, in order to run as a non-privileged user (to avoid UID/GID conflicts inside the container), this would need to be changed to a high port (8080?).  could make it a config option, but ideally the released image should also be adjusted to run as a non-root user

## UI and Admin UI Local Dev

- Local Dev services:
  - `node` image that mounts source code and runs `ng serve`

## General CI Improvements

Right now it looks like CI does not build on push or PRs, it just does tags.  I would like to make CI more robust, by building testable images.  I understand tests may still need to be written, but this will at least provide a good option down the road, and also ensure that code compiles.

A folder structure that I have used in the past that works well is:

```
repo-root/
  docker-compose.yaml          # docker-compose for running local dev env
  cicd/
    docker/
      dev/
        Dockerfile             # local development Dockerfile
        stage/                 # assets for local development image
      sdk/
        docker-compose.yaml    # docker-compose for building SDK image
        Dockerfile             # local development Dockerfile
        stage/                 # assets for local development image
      release/
        docker-compose.yaml    # docker-compose for building Release image
        Dockerfile             # local development Dockerfile
        stage/                 # assets for local development image
```

A developer can generally clone the repository, and run `docker-compose up --build` to get up-and-running with local development

Example of the SDK/Release images are:

- backend:
  - SDK: `golang:1.13-alpine`
  - Release: `alpine` with final binary copied into it
- frontends:
  - SDK: `node:lts-alpine`
  - Release: `nginx:stable-alpine` with dist/ copied into it

Think of it as a multistage build, except there is a break in between stages to run tests against the SDK image.  The CI process runs the following:

```
# every push and pull request

docker-compose build -f cicd/docker/sdk/docker-compose.yaml
docker run --rm hobbyfarm/service:sdk "npm test" or "go test"

docker-compose build -f cicd/docker/sdk/docker-compose.yaml

# if this is a tag or branch that should be released
docker tag hobbyfarm/service:release hobbyfarm/service:${tag}
docker push hobbyfarm/service:${tag}
```

I'm fairly far along coding this up in a fork, and can open PRs in the next couple days for it...

**Comment by ebauman** [comment]
Hi @caleblloyd thanks for opening this!

First off, thanks for working on HobbyFarm. We really appreciate any & all efforts to move this thing forward. BoxBoat has been an awesome force in this project and I can't thank them enough for their work. 

A few thoughts regarding this, in no particular order:
* I would prefer to use k3s/k3d instead of `kind`. Based purely on startup time alone, `k3d` can create a cluster in ~.5s, whereas `kind` via their project page is at like 20s. I also suspect - though don't have any empirical evidence to prove - that `k3d` is much lighter weight than k3s.
* I think changing `gargantua` to listen on port 8000 or something makes sense. 

Otherwise, I like this approach. Could you share a sample `docker-compose.yml` so I can get a better feel for how that flow would work?

**Comment by ebauman** [comment]
Never mind re: docker-compose. I see your PR now. 
Let me know your thoughts on k3d.

**Comment by caleblloyd** [comment]
Yes, let me explore flipping `kind` to `k3d`

**Comment by caleblloyd** [comment]
Status so far with the 3 open PRs:

![hf](https://user-images.githubusercontent.com/2414837/76362733-98b90b80-6332-11ea-950a-98a0ea545502.png)

Still need to consider some things:
- garg dev docker-compose:
  - run another container (or process in same container - would be lighter weight) for garg-shell
- is there a terraform controller for k3d that could spin up k3d "VMs"?  I guess that could go along `k3d` and `kubectl` in `hobbyfarm/hobbyfarm`
- Admn UI will basically be the same thing as UI, so once UI is reviewed I can port that over

**Comment by caleblloyd** [comment]
OK, switch to k3d complete in the PRs.  Great suggestion, it starts faster, it's lighter weight, and is less complex to initialize

I'm going to address these items before ready for merge:

garg dev docker-compose:
- run another container (or process in same container - would be lighter weight) for garg-shell

fake terraform controller:
- run a `sshd` container in `hobbyfarm/hobbyfarm`
- run a fake `terraform` controller in `hobbyfarm/hobbyfarm` that connects every "vm" to the `sshd` container

Down the road I think we need to provide the ability to connect to "vms" via subprocess pipes instead of just `sshd`.  This would allow for using `sh` as fake VM, or allow for connecting to Kube pods instead of full VMs via `kubectl exec`

**Comment by ebauman** [comment]
On the subject of fake terraform controller

I am working on a module that would allow for deployment of a tiny `sshd` pod, whose only job is to allow connections. It would allow for full testing of the terraform controller, provisioning, and websocket shell w/o having to spin up a full VM.

I expect to have more info / code on that in the next day or two.

**Comment by caleblloyd** [comment]
I updated the PRs and they now include:

garg dev docker-compose:
- run another process in same container for garg-shell

fake terraform controller:
- run a `sshd` container in `k3d`
- run a `tf-git` container in `k3d` to host a `sshd` terraform module that adds the public key for all vms to the `sshd` container

![image](https://user-images.githubusercontent.com/2414837/76659255-f8a7f000-6586-11ea-8025-38b7979dd2dd.png)

The PRs are all working together, except for some reason dynamic bind not working.  Probably an issue with my seed data, I'll continue to debug.

Other than that, these are ready for review:
- https://github.com/hobbyfarm/hobbyfarm/pull/79
- https://github.com/hobbyfarm/gargantua/pull/46
- https://github.com/hobbyfarm/ui/pull/59

**Comment by ebauman** [comment]
@caleblloyd awesome! I will review soon as I can. 
Appreciate this.

**Comment by caleblloyd** [comment]
Dynamic bind working now, was an issue with one of the CRDs I was seeding.  #79 updated

**Comment by hall** [comment]
Looks like everything's merged. Thanks, @caleblloyd!
