### ISSUE TITLE
Should we remove the `Info` tab?

### ISSUE THREAD

**Issue by hall** [hobbyfarm/hobbyfarm#8]
I'm not sure if this tab serves a particular purpose but I'm thinking it just adds more cruft.

![DeepinScreenshot_select-area_20200106150550](https://user-images.githubusercontent.com/32495955/71845352-08571400-30c0-11ea-86c0-e73a702bcfa5.png)

@ebauman, is there a good reason to keep it or can I get rid of it?

**Comment by jggoebel** [comment]
Info Tab removed in https://github.com/hobbyfarm/ui/pull/83

**Comment by jggoebel** [comment]
The info tab was removed.
