### ISSUE TITLE
Stop hardcoding "ubuntu" as shell user

### ISSUE THREAD

**Issue by ebauman** [hobbyfarm/hobbyfarm#83]
https://github.com/hobbyfarm/gargantua/blob/252c60aa289ba89c3fca3d00cf4c9ae491951518/pkg/shell/shell.go#L91

This should be configurable, probably as a template mapping property on the environment.

**Comment by ibrokethecloud** [comment]
Do we want to look at adding annotations on `VirtualMachineTemplateSpec` to contain ssh user? This will avoid having to change the types and we should still be able to make the ssh function more dynamic

**Comment by ebauman** [comment]
IMO, yes, that's the best way to fix this.
