### ISSUE TITLE
Creating Scheduled Events throws silent 500 error

### ISSUE THREAD

**Issue by wjimenez5271** [hobbyfarm/hobbyfarm#9]
I was creating a scheduled event with similar parameters to many others I've done, but two times in a row it throw 500 errors (silently, had to check the developer console to see)

![Screen Shot 2020-01-06 at 9 59 23 AM](https://user-images.githubusercontent.com/322834/71837578-a371ce80-306b-11ea-9cea-7cc59b76d29c.png)

**Comment by hall** [comment]
If this reoccurs, please post the http response from garg (and/or the corresponding error log from garg). Hopefully, we can fix the underlying issue but we can at least bubble up the error to the UI.

**Comment by jggoebel** [comment]
There are no new updates on this issue for a long time. I will close this issue until we have further updates.
